frase = "   Curso em video Python   "
print(frase[3])
print(frase[3:13])
print(frase[::2])
print(frase[1:21:2])
print(frase.count("o"))
print(frase.count("O"))
print(frase.upper().count("o"))
print(frase.upper().count("O"))
print(len(frase))
print(len(frase.strip()))
print(frase.replace("Python","Roblox"))
print("Curso" in frase)
print(frase.find("Curso"))
print(frase.lower().find("Curso"))
frase = frase.replace("Python","Roblox")
dividido = frase.split()
print(dividido)
print(dividido[0])
print(dividido[0][3])
